logging:
  level: info

welcome-message: false

# Web server
web:
  host: "0.0.0.0"
  port: $PORT

## Parsers
parsers: []

## Connector modules
connectors:
  - name: websocket
    bot-name: "opsdroid-demo"

#databases:
#  - name: mongo
#    host: $MONGO_HOST
#    database: opsdroid

## Skill modules
skills:
  ## API.AI (https://github.com/opsdroid/skill-apiai)
  - name: apiai

  ## Last seen (https://github.com/opsdroid/skill-seen)
  - name: seen

  ## Dance (https://github.com/opsdroid/skill-dance)
  - name: dance

  ## Loud noises (https://github.com/opsdroid/skill-loudnoises)
  - name: loudnoises

  - name: heroku
    path: /opt/opsdroid/skills/heroku
    app-name: opsdroid-demo
